# collections
collections:
  posts:
    title: Posts
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    header_feature_image:
    caption:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    header_feature_image:
    caption:

# SITE CONFIGURATION
baseurl: ''  #leave this alone
url: "https://eyescroll.netlify.app"   #change this to yours
repository: eyescroll/eyescroll.github.io
# twitter_username: pageboy  #change to your own twitter account
lang: en_gb

  # Icons
  # If you have any of these accounts add them in here
rss: false  # Make sure you created a feed.xml with feed.xml layout

# Scripts / Features
google_analytics: # Tracking ID, e.g. "UA-000000-01"
disqus_shortname: # create an account on disqus.com for comments

# Localization strings
str_follow_on: "Follow on"
str_rss_follow: "Follow RSS feed"
str_share_on: "Share on"
str_add_to: "Add to"
str_email: "Email"
str_tweet: "Tweet"
str_pin_it: "Pin it"
str_next_post: "Next post"
str_previous_post: "Previous post"
str_next_page: "Next"
str_previous_page: "Prev"
str_javascript_required_disqus: "Please enable JavaScript to view comments."

# Post navigation
post_navigation: true

# PAGINATION
paginate: 10
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
permalink: /posts/:title/
highlighter: rouge
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]
exclude: [".jekyll-cache", "Gemfile", "README.md"]
github: [metadata]
