description: A website with a blog
header_text: Brookes Dream Blog
footer_text: Copyright 2020 Chris Jennings
header_feature_image: /uploads/books4screen.jpg
gridlayout: false
# items:
#   - name: Blog
#     siteurl: /blog/
#     tab: false
logo: /uploads/face.jpg
upzoom: true
favicon: /uploads/favicon.ico
title: Chris Jennings
