general:
  title: Chris Jennings # site's title
  description: "A website with a blog" # used by search engines
  header_text: "Brookes Dream Blog"
  footer_text: "Copyright 2020 Chris Jennings"
  header_feature_image: /uploads/water.jpg
  gridlayout: false
  logo: /uploads/face.jpg
  favicon: /uploads/favicon.ico

social:
  twitter: pageboy
  instagram: pagebuoy
  facebook:
  disqus_shortname:
  flickr:
  soundcloud:
  pinterest:
