general:
  header_feature_image: /uploads/books4screen.jpg
  logo: /uploads/face.jpg
  upzoom: false
  gridlayout: false
  footer_text: Copyright 2020 Chris Jennings
  favicon: /uploads/favicon.ico
  title: Chris Jennings
  description: A website with a blog
  header_text: Brookes Dream Blog
social:
  youtube: null
  soundcloud: null
  facebook: null
  flickr: null
  disqus_shortname: null
  email_address: chrisjennings@me.com
  instagram: pagebuoy
  twitter: pageboy
  pinterest: null
  tumblr: null
  linkedin: null
share_buttons:
  facebook: true
  twitter: true
  tumblr: null
  pinterest: null
  linkedin: null
  email_address: true
  instagram: true
menuitems:
  items:
    - name: Editor
      siteurl: /admin/
      tab: false
items:
  - name: test
    siteurl: google.com
    tab: true
