general:
  title: Chris Jennings
  description: A website with a blog
  header_text: Brookes Dream Blog
  footer_text: Copyright 2020 Chris Jennings
  header_feature_image: /uploads/904309dc-3438-410f-841f-038e4d9f1abc.jpeg
  gridlayout: false
  logo: /uploads/face.jpg
  favicon: /uploads/favicon.ico
social:
  email_address:
  twitter: pageboy
  instagram: pagebuoy
  facebook: null
  disqus_shortname: null
  flickr: null
  soundcloud: null
  pinterest: null
  YouTube:
