general:
  title: Chris Jennings
  description: A website with a blog
  header_text: Brookes Dream Blog
  footer_text: Copyright 2020 Chris Jennings
  header_feature_image: /uploads/books4screen.jpg
  gridlayout: false
  upzoom: true
  logo: /uploads/face.jpg
  favicon: /uploads/favicon.ico
social:
  youtube: null
  soundcloud: null
  facebook: null
  flickr: null
  disqus_shortname: null
  email_address: chrisjennings@me.com
  instagram: pagebuoy
  twitter: pageboy
  pinterest: null
  tumblr: null
  linkedin: null
share_buttons:
  facebook: true
  twitter: true
  tumblr: null
  pinterest: null
  linkedin: null
  email_address: true
  instagram: true
