backend:
  name: github
  repo: eyescroll/eyescroll.github.io # Path to your GitHub repository
  branch: master # Branch to update (master by default)
  site_domain: eyescroll.netlify.app

show_preview_links: false
display_url: https://eyescroll.netlify.app
logo_url: https://eyescroll.netlify.app/uploads/face.jpg

# This line should *not* be indented
media_folder: "uploads" # Media files will be stored in the repo under /uploads
public_folder: "/uploads"

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    label_singular: "Post"
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    media_folder: "/uploads"
    public_folder: "/uploads"
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Published", name: "published", widget: "boolean", required: false}
      - {label: "Featured Image", name: "header_feature_image", widget: "image", required: false}
      - {label: "Caption", name: "caption", widget: "string", required: false}
      - {label: "Comments", name: "comments", widget: "boolean", required: false, hint: "If you setup your Disqus account then turn this on"}
      - {label: "Body", name: "body", widget: "markdown"}


  - name: "pages"
    publish_mode: editorial_workflow
    label: "Pages" # Used in the UI
    label_singular: "Page"
    folder: "pages/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    media_folder: "uploads"
    public_folder: "/uploads"
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "header_feature_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "data"
    publish_mode: normal
    label: "Settings"
    editor:
      preview: false
    files:
      - label: "Settings for your Web site"
        name: "settings"
        description: "Unfold these groups and configure the settings for your site"
        file: "_data/settings.yml"
        fields:
          - label: "General Settings"
            name: "general"
            widget: "object"
            hint: "These are essential settings for your site"
            collapsed: false
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
                required: true
              - label: "Description"
                name: "description"
                widget: "string"
                required: false
              - label: "Text in the Banner"
                name: "header_text"
                widget: "string"
                required: false
              - label: "Text in the Footer"
                name: "footer_text"
                widget: "string"
                required: true
                hint: "You can put the copyright info in here"
              - label: "Home Page Image"
                name: "header_feature_image"
                widget: "image"
                allow_multiple: false
                hint: "This image will show on the home page. It needs to be a minimum of 900 pixels wide."
                required: false
              - label: "Grid Layout"
                name: "gridlayout"
                widget: "boolean"
                required: false
                hint: "You can choose to show the posts on the home page in a grid rather than just lined up vertically"
          - label: "Your Social Media Accounts"
            name: "social"
            widget: "object"
            hint: "Put any social media accounts in here so that you can show the icons on your web site"
            collapsed: true
            fields:
              - label: "Twitter"
                name: "twitter"
                widget: "string"
                required: false
              - label: "Instagram"
                name: "instagram"
                widget: "string"
                required: false
              - label: "Facebook"
                name: "facebook"
                widget: "string"
                required: false
              - label: "Disqus"
                name: "disqus_shortname"
                widget: "string"
                required: false
                hint: "Once you have a disqus account you can put the short name in here."
              - label: "Flickr"
                name: "flickr"
                widget: "string"
                required: false
              - label: "Soundcloud"
                name: "soundcloud"
                widget: "string"
                required: false
              - label: "Pinterest"
                name: "pinterest"
                widget: "string"
                required: false
